# Generated by Django 2.2.1 on 2019-09-24 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190924_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 17, 30, 2, 161828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 17, 30, 2, 155828, tzinfo=utc)),
        ),
    ]
